# Demo 2, Term Frequency - Inverse Document Frequency

TF-IDF is similar to bag of words, however the final counts are divided by the number of documents in the corpus.

It can be useful for identifying words that are not well represented by your corpus of data, that may need more samples provided.

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import os
try:
    os.chdir("Sonnets")
except:
    pass

Use the same data-loader as before.

In [12]:
file_list = os.listdir('.')
for file in file_list:
    if file.startswith("Sonnet") and file.endswith(".txt"):
        pass
    else:
        print(file)
        file_list.remove(file)
file_list.sort()

shakespeares-sonnets_TXT_FolgerShakespeare.txt
stopwords.txt


We must tell the TF-IDF vectorizer algorithm what kind of data to expect, in this case, we're using files, so we give the algorithm "filename" as an input.

In [13]:
tf_idf_algorithm = TfidfVectorizer("filename")
tfidf = tf_idf_algorithm.fit_transform(file_list)

In [14]:
print(type(tfidf))

<class 'scipy.sparse.csr.csr_matrix'>


In [15]:
numpy_tfidf = tfidf.toarray()

In [16]:
print(numpy_tfidf.shape)

(154, 3074)


In [17]:
first_sonnet = numpy_tfidf[0]
print(first_sonnet)
print(first_sonnet.shape)

[0. 0. 0. ... 0. 0. 0.]
(3074,)


In [18]:
#Find non-zero
np.nonzero(numpy_tfidf[0])

(array([   7,  101,  137,  139,  197,  199,  210,  350,  362,  371,  376,
         378,  442,  516,  520,  556,  570,  617,  669,  692,  771,  800,
         812,  909,  919,  930,  964, 1003, 1020, 1081, 1085, 1091, 1108,
        1143, 1167, 1262, 1270, 1290, 1360, 1365, 1512, 1515, 1588, 1593,
        1631, 1644, 1731, 1738, 1757, 1791, 1798, 1801, 1825, 1902, 2168,
        2183, 2262, 2315, 2438, 2442, 2515, 2562, 2604, 2616, 2617, 2618,
        2628, 2636, 2644, 2648, 2669, 2670, 2677, 2685, 2697, 2897, 2908,
        2937, 2993, 2996, 3023], dtype=int64),)

In [9]:
#Un-tokenize word
print(tf_idf_algorithm.get_feature_names()[151])

astonished


In [23]:
#print out the tf-idf value for a word
print(np.nonzero(numpy_tfidf[0]))

(array([   7,  101,  137,  139,  197,  199,  210,  350,  362,  371,  376,
        378,  442,  516,  520,  556,  570,  617,  669,  692,  771,  800,
        812,  909,  919,  930,  964, 1003, 1020, 1081, 1085, 1091, 1108,
       1143, 1167, 1262, 1270, 1290, 1360, 1365, 1512, 1515, 1588, 1593,
       1631, 1644, 1731, 1738, 1757, 1791, 1798, 1801, 1825, 1902, 2168,
       2183, 2262, 2315, 2438, 2442, 2515, 2562, 2604, 2616, 2617, 2618,
       2628, 2636, 2644, 2648, 2669, 2670, 2677, 2685, 2697, 2897, 2908,
       2937, 2993, 2996, 3023], dtype=int64),)
(154,)


In [27]:
print(numpy_tfidf[:,7].shape)
print(numpy_tfidf[:,7])
print(np.sum(numpy_tfidf[:,7]))

(154,)
[0.11337761 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.11211088 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.11779593 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.  

In [31]:
TF_IDF = []
for i in range(0,153):
    TF_IDF.append(np.sum(numpy_tfidf[:,i]))

In [35]:
print(min(TF_IDF))
print(TF_IDF.index(min(TF_IDF)))

0.10969418531007252
52


In [36]:
print(tf_idf_algorithm.get_feature_names()[52])

afar


In [37]:
print(numpy_tfidf[:,52])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         